# Generated by Django 4.1 on 2022-09-02 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lavadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('telefono_aux', models.CharField(max_length=15, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('A', 'Abierto'), ('C', 'Cerrado'), ('I', 'Inactivo')], default='C', max_length=1)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('M', 'Moto'), ('A', 'Auto'), ('P', 'Pickup'), ('C', 'Camion')], max_length=1)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lavadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lavaderos.lavadero')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miercoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sabado'), ('D', 'Domingo')], max_length=1)),
                ('desde', models.TimeField()),
                ('hasta', models.TimeField()),
                ('lavadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lavaderos.lavadero')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tarifa',
            constraint=models.UniqueConstraint(fields=('tipo', 'lavadero'), name='unique_tipo_lavadero_combination'),
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.UniqueConstraint(fields=('lavadero', 'dia'), name='unique_lavadero_dia_combination'),
        ),
    ]
