# Generated by Django 4.1 on 2022-09-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavaderos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavadero',
            name='encargado',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='lavadero',
            name='imagen',
            field=models.BinaryField(null=True),
        ),
    ]
