# Generated by Django 4.1 on 2022-09-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavaderos', '0003_alter_lavadero_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavadero',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
