# Generated by Django 4.1 on 2022-09-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavaderos', '0005_alter_lavadero_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
