# Generated by Django 4.1 on 2022-09-30 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lavaderos', '0006_alter_tarifa_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudLavadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('M', 'Moto'), ('A', 'Auto'), ('P', 'Pickup'), ('C', 'Camion')], max_length=1)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('aceptado', models.BooleanField(default=None, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lavadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lavaderos.lavadero')),
            ],
        ),
    ]
